### PR TITLE
Regression reconfigure

### PR DESCRIPTION
**Pull request by msternat**
Revised the regression test process completely.

- removed misc. files from regression testing subdirectories
- Moved existing test outputs into reference files
- added modified version of NJOY Python diffing utility, removed execution step and updated several other parts
- Updated regression testing script to search for eligible input files, then run, then perform diff. Script exits on failed diff.
- Update relative and absolute tolerance for diff to 1E-4, can iterate lower as it passes the CI automated tests.

### CODE REVIEW

**Comment by msternat** [comment]
Notes: test case 3 currently has issues depending on what compiler is used. Comparing GCC 6.1 vs GCC 9.2, we get the following diffs:

```
*** SNL-NJOY-2016_referenceTape37 ***
--- SNL-NJOY-2016_Test_Tape37 ---
***************
*** 24 ***
!/Helvetica findfont [   0.00  21.60 -21.60   0.00 0. 0.] makefont setfont
--- 24 ---
!/Helvetica findfont [  -0.00  21.60 -21.60   0.00 0. 0.] makefont setfont
***************
*** 27 ***
!/Helvetica findfont [   0.00  21.60 -21.60   0.00 0. 0.] makefont setfont
--- 27 ---
!/Helvetica findfont [  -0.00  21.60 -21.60   0.00 0. 0.] makefont setfont
***************
*** 30 ***
!/Helvetica findfont [   0.00  21.60 -21.60   0.00 0. 0.] makefont setfont
--- 30 ---
!/Helvetica findfont [  -0.00  21.60 -21.60   0.00 0. 0.] makefont setfont
...
```
Clearly the only difference is a negative sign on the zeros. I'm going to currently overwrite the reference test with the GCC 9.2 version to align with the automated testing compiler. Similar issue found on test 5 - Tape35.

**Comment by msternat** [comment]
@sandialabs/snl-njoy-2016, running into some major issues with GCC 9. Looks like the existing code is failing for many runs, independent of my changes. This is visible here from the last updates:

https://github.com/sandialabs/NJOY2016/runs/4682930513?check_suite_focus=true

You can mouse to the regression test stage and unfold, which shows that many of these cases were and still are failing when building with GCC 9. Look for "cp: cannot stat 'tapeXX': No such file or directory" to see which ones have failed. Previously, this did not cause the automated testing to fail, but I've forced this behavior with the diffing utility I've added. 

Digging into the actual GCC 9 error, which is not visible from the automated CI, I'm seeing the following when running myself running Debug mode:

```

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7f7aa63903ef in ???
#1  0x7f7aa77a5aab in convr
	at /ascldap/users/mrstern/NJOY2016/Git-Clone/NJOY2016/src/acefc.f90:4142
#2  0x7f7aa77d39e6 in __acefc_MOD_acetop
	at /ascldap/users/mrstern/NJOY2016/Git-Clone/NJOY2016/src/acefc.f90:159
#3  0x7f7aa781a7c8 in __acem_MOD_acer
	at /ascldap/users/mrstern/NJOY2016/Git-Clone/NJOY2016/src/acer.f90:424
#4  0x403a09 in njoy
	at /ascldap/users/mrstern/NJOY2016/Git-Clone/NJOY2016/src/main.f90:407
#5  0x403bff in main
	at /ascldap/users/mrstern/NJOY2016/Git-Clone/NJOY2016/src/main.f90:177

```
The errors on other tests are not always the same. We may have some compiler compatibility issues at hand.

I think we should address the issue separate from this branch. I'll propose 2 options to move forward:

1. Merge the changes while failing, preserving excluding test 25 and 33
2. Merge the changes while passing, excluding all failing cases (quite a few)

**Comment by msternat** [comment]
I've tested with GCC 6.1 and GCC 7.3, all cases pass without issue. So something specific to GCC 9 is at fault here. The original NJOY2016 automated tested process uses GCC 9, so that's what I went with on ours. We should ensure sustained compiler compatibility, but it can get expensive to dig into.

**Comment by msternat** [comment]
I've addressed the GCC 9+ issues by pulling in changes from the main NJOY2016 repo. We're currently able to pass the automated testing for Release mode on Linux, but failing the Debug build.

**Comment by msternat** [comment]
I've removed the Debug builds due to GitHub image failures. These are not reproducable on my local machine, but Test 21 keeps failing on the Debug automated runs. There may be patches from the main/NJOY2016 to resolve this. I'm considering this a separate issue and this pull request is ready for review (finally). Sorry for all the email spam this thing probably sent everyone.

**Review by NicholasAsp — COMMENTED** [review]
I looked over all the changes and everything seems alright. There are some reference tape value changes like in Test 16 tape 26 but I don't see those mattering. However most of these changes are just renaming reference tapes and adding the diff.py file.

**Pull request merged**
